src/Spg.MusicPalace.FrontEnd/Controllers/AlbumsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Spg.MusicPalace.Application;
using Spg.MusicPalace.Application.AlbumApp;
using Spg.MusicPalace.Application.ArtistApp;
using Spg.MusicPalace.Domain.Exceptions;
using Spg.MusicPalace.Dtos;

namespace Spg.MusicPalace.FrontEnd.Controllers
{
    public class AlbumsController : Controller
    {
        private readonly IAlbumService _albumService;
        private readonly IArtistService _artistService;

        public AlbumsController(IAlbumService albumService, IArtistService artistService)
        {
            _albumService = albumService;
            _artistService = artistService;
        }

        [HttpGet()]
        public IActionResult Index(string filter, string currentFilter, string sortOrder, int pageIndex = 1)
        {
            filter = filter ?? currentFilter;

            ViewData["sortParamTitle"] = sortOrder == "title" ? "title_desc" : "title";
            ViewData["sortParamArtist"] = sortOrder == "artist" ? "artist_desc" : "artist";
            ViewData["sortParamSongAmount"] = sortOrder == "songamount" ? "songamount_desc" : "songamount";

            _albumService
                .UseContainsFilter(filter)
                .UseSorting(sortOrder)
                .UsePaging(pageIndex, 10);

            PagenatedList<AlbumDto> model = _albumService.ListAll();
            return View((model, filter));
        }

        [HttpGet()]
        public IActionResult Create()
        {
            ViewBag.artists = new SelectList(_artistService.ListAll(), "Guid", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(NewAlbumDto model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.artists = new SelectList(_artistService.ListAll(), "Guid", "Name");
                return View(model);
            }
            try
            {
                _albumService.Create(model);
                return RedirectToAction("Index", "Songs");
            }
            catch (AlbumServiceCreateException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            catch (ServiceValidationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            ViewBag.artists = new SelectList(_artistService.ListAll(), "Guid", "Name");
            return View(model);
        }

        [HttpGet()]
        public IActionResult Details(Guid id)
        {
            AlbumDto model = _albumService.Details(id);
            return View(model);
        }
    }
}

src/Spg.MusicPalace.FrontEnd/Views/Albums/Create.cshtml
@model Spg.MusicPalace.Dtos.NewAlbumDto

<form method="post">
    <div asp-validation-summary="All"></div>
    <label asp-for="Title">Name:</label>
    <input asp-for="Title" type="text" />
    <br />    
    <label asp-for="Artist">Artist:</label>
    <select asp-for="Artist" asp-items="@ViewBag.artists">Artist</select>    
    <hr />

    <button type="submit">Create</button>
</form>
<form method="get">    
    <button type="submit" asp-controller="Albums" asp-action="Index">Back</button>
</form>

src/Spg.MusicPalace.FrontEnd/Views/Albums/Details.cshtml
@model Spg.MusicPalace.Dtos.AlbumDto

<h3>Details of album @Model.Title</h3>

@if (Model is not null)
{
<dl>
    <dt>Title:</dt>
    <dd>@Model.Title</dd>
    <dt>Artist:</dt>
    <dd>@Model.Artistname</dd>    
</dl>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Songs</th>
        </tr>
    </thead>
    <tbody>
        @foreach(string item in @Model.SongTitles)
        {
            <tr>
                <td>@item.ToString()</td>
            </tr>
        }
    </tbody>
</table>
<dl>    
    <dt>Guid:</dt>
    <dd>@Model.Guid</dd>   
    
    <a asp-controller="Albums" asp-action="Index">Back</a>
</dl>
}
else
{
    <div class="alert alert-danger" role="alert">
        No data found!
    </div>
}

src/Spg.MusicPalace.FrontEnd/Views/Albums/Index.cshtml
@using Spg.MusicPalace.Application;
@model (PagenatedList<Spg.MusicPalace.Dtos.AlbumDto> albums, string filter)

@{
    string hasPrevious = Model.albums.HasPreviousPage ? "" : "disabled";
    string hasNext = Model.albums.HasNextPage ? "" : "disabled";
}

<h3>All Albums</h3>

@if (Model.albums is not null 
    && Model.albums.Count > 0)
{
    <form method="get">
        <label>FilterName</label>
        <input name="filter" value="@Model.filter">
        <button type="submit">Go</button>
    </form>

    <a 
        asp-action="Index" 
        asp-route-currentSubject="@Model.filter" 
        asp-route-pageIndex="@(Model.albums.PageIndex - 1)"
        class ="btn btn-secondary @hasPrevious">Previous
    </a>
    <a 
        asp-action="Index" 
        asp-route-currentSubject="@Model.filter" 
        asp-route-pageIndex="@(Model.albums.PageIndex + 1)"
        class ="btn btn-secondary @hasNext">Next
    </a>

    <p>
        Page @Model.albums.PageIndex of @Model.albums.TotalPages
    </p>

    <form method="get">
        <button type="submit" asp-controller="Albums" asp-action="Create">Create</button>
    </form>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Artist</th>
            <th>Songs</th>
            <th>Links</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Spg.MusicPalace.Dtos.AlbumDto item in @Model.albums)
        {
            <tr>
                <td>@item.Title</td>
                <td>@item.Artistname</td>
                <td>@item.SongAmount</td>
                <td>
                    <a asp-controller="Albums" asp-action="Details" asp-route-id="@item.Guid">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

}
else
{
    <div class="alert alert-danger" role="alert">
        No data found!
    </div>
}